### PR TITLE
Fix loopclosure waring - add variable captured in loops to function as params

### LINKED ISSUE #35: Get Cloud Providers/Scalers API returns only 1 entry
Step to reproduce: 
* Create 2 cloud providers
* GET /clouds

Expected result: 
* Get body contains 2 cloud providers

Actual result:
* Only 1 cloud provider returned

### PR DESCRIPTION
**Pull request by vtdat**
add variable captured in loops to function as params

Fix #35

### CODE REVIEW

File: api/cloud.go [hunk 1]
```diff
@@ -104,10 +104,10 @@ func (a *API) listClouds(w http.ResponseWriter, req *http.Request) {
 	clouds = make(map[string]interface{}, len(resp.Kvs))
 	for _, ev := range resp.Kvs {
 		wg.Add(1)
-		go func() {
+		go func(evb []byte, evk string) {
```
Comment (ntk148v) [inline api/cloud.go]: NIT: should be `evv` to match w/ `evk` :smile:
